spring.datasource.url=jdbc:mysql://localhost:3306/student_health
spring.datasource.username=root
spring.datasource.password=mysql@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8083
